### ISSUE TITLE
[BUG] build.yaml configuration instead of pubspec.yaml

### ISSUE THREAD

**Issue by zs-dima** [FlutterGen/flutter_gen#114]
build.yaml intended for generators configuration.
So could be nice to use build.yaml configuration instead of pubspec.yaml configuration.

❌ **Bad**  
```dart
pubspec.yaml
```

⭕️ **Good**  
```dart
build.yaml
```

**Comment by lcdsmao** [comment]
You can specify the yaml file via:
```
fluttergen -c path/to/your/yaml/flie.yaml
```

**Comment by zs-dima** [comment]
@lcdsmao thans for looking into, but I mean default configuration in the build.yaml file

**Comment by zs-dima** [comment]
@lcdsmao here build_runner documentation 
> Builders are configured with a build.yaml
https://pub.dev/packages/build_runner

**Comment by lcdsmao** [comment]
@zs-dima 
What's your use case here?
Can you give some examples?

**Comment by zs-dima** [comment]
@ I mean default way to configure builders libraries.

Here your documentation:


## Configuration file

[FlutterGen] generates dart files based on the key **`flutter`** and **`flutter_gen`** of [`pubspec.yaml`](https://dart.dev/tools/pub/pubspec).  
Default configuration can be found [here](#default-settings). 

```yaml
# pubspec.yaml
# ...

flutter_gen:
```

but it have to be:

## Configuration file

[FlutterGen] generates dart files based on the key **`flutter_gen`** of [`build.yaml`].  
Default configuration can be found [here](#default-settings). 

```yaml
# build.yaml
# ...
    builders:
# ...
      flutter_gen:
# ...
```

**Comment by noga-dev** [comment]
> @zs-dima What's your use case here? Can you give some examples?

Probably to be being able to aggregate all codegen builders in the same command via: ```flutter pub run build_runner watch --delete-conflicting-outputs``` rather than individually running flutter_gen and other packages. Since in build.yaml you can specify the commands for each builder like: 
```
targets:
  $default:
    builders:
      slang_build_runner:
        options:
      flutter_gen:
        options:
      etc....
```
