### ISSUE TITLE
Select only some folders to generate assets

### ISSUE THREAD

**Issue by elianortega** [FlutterGen/flutter_gen#132]
Is it possible to select only some folders and not all from `assets/`?

with this I mean overriding the default 
```yaml
flutter:
  assets:
    - ...
```

and tell `flutter_gen` to generate the assets only of some directories
