### ISSUE TITLE
Error: Method not found: '$checkedCreate'

### ISSUE THREAD

**Issue by vishalrao8** [FlutterGen/flutter_gen#139]
On running the build runner command I am getting these errors.

![Screenshot (138)](https://user-images.githubusercontent.com/27092065/137958040-e917c584-bb17-4b31-93f6-d59a518c6431.png)

My dev dependencies are:
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  flutter_gen_runner: ^4.0.0
  lint: ^1.7.2
  import_sorter: ^4.6.0
```
Flutter doctor result:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1288], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.61.1)
```

Commands tried:
```
flutter clean
flutter pub get
flutter pub global activate flutter_gen
flutter pub run build_runner build --delete-conflicting-outputs
```

**flutter pub global activate flutter_gen**
```
Package flutter_gen is currently active at version 4.0.0.
Resolving dependencies...
The package flutter_gen is already activated at newest available version.
To recompile executables, first run `global deactivate flutter_gen`.
Installed executable fluttergen.
Activated flutter_gen 4.0.0.
```
