### ISSUE TITLE
Generate constants

### ISSUE THREAD

**Issue by fzyzcjy** [FlutterGen/flutter_gen#185]
For example,

```
class $AssetsBlobLottieGen {
  const $AssetsBlobLottieGen();

  /// File path: assets/blob/lottie/bug.json
  String get bug => 'assets/blob/lottie/bug.json';
}
```

can be 

```
class $AssetsBlobLottieGen {
  const $AssetsBlobLottieGen();

  /// File path: assets/blob/lottie/bug.json
  const bug = 'assets/blob/lottie/bug.json';
}
```

Similar holds for AssetGenImage and so on.

Then we can use that value as constant happily. For example,

```
      child: Image(
        image: Assets.icon.icon,
        width: 64,
        height: 64,
      ),
```

can be 

```
      child: const Image( // <-- notice "const"
        image: Assets.icon.icon,
        width: 64,
        height: 64,
      ),
```

**Comment by lcdsmao** [comment]
It is impossible to declare const field without static modifier:

<img width="693" alt="Screen Shot 2022-01-06 at 9 20 25" src="https://user-images.githubusercontent.com/13031690/148308442-bba51203-07ed-4ca9-87e1-19dae09e0ace.png">

If you want it to be const, prefer to set `assets.style` to be either `camel-case` or `snake-case`.

```yaml
flutter_gen:
  assets:
    package_parameter_enabled: false
    # Optional
    # Avaliable values:
    # - camel-case
    # - snake-case
    # - dot-delimiter
    style: dot-delimiter
```

Example:
https://github.com/FlutterGen/flutter_gen/blob/1a1ba2cb6d31a6c69a555151093ec3b67eb89a37/packages/core/test_resources/actual_data/assets_camel_case.gen.dart#L14-L15
