### ISSUE TITLE
gen runner fails with Bad state: No element

### ISSUE THREAD

**Issue by felix-barz-brickmakers** [FlutterGen/flutter_gen#268]
The current version of `flutter_gen_runner` failes with the following error:

```
[SEVERE] flutter_gen_runner:flutter_gen_runner on $package$ (cached):

Bad state: No element
[SEVERE] Failed after 16.0s
```

Running the build runner in verbose mode does not reveal anything else about the error.

I tried deleting all image and font assets, but that did not fix the problem, so it seems it has nothing to do with a broken file or something like that. I attached the pubspec and lockfile of the project for reference.

[pubspec.yaml.txt](https://github.com/FlutterGen/flutter_gen/files/8876742/pubspec.yaml.txt)
[pubspec.lock.txt](https://github.com/FlutterGen/flutter_gen/files/8876741/pubspec.lock.txt)

**Comment by jl-insiders** [comment]
Thanks, we are getting this also.

FlutterGen v4.3.0 Loading ... pubspec.yaml
[SEVERE] flutter_gen_runner:flutter_gen_runner on $package$:

Bad state: No element

**Comment by felix-barz-brickmakers** [comment]
New infos: I found the position in the code where the exception is throw:
It happens in https://github.com/FlutterGen/flutter_gen/blob/main/packages/runner/lib/flutter_gen_runner.dart#L62

Apparently, the `buildStep.findAssets` fails to find the pubspec.yaml. I checked with the debugger, and the `config.pubspecFile.path` correctly resolves to `"pubspec.yaml"`

![Bildschirmfoto 2022-06-24 um 09 01 09](https://user-images.githubusercontent.com/60686992/175480939-b2812900-3b91-49d8-9c0d-db67608bded1.png)

Note: This first broke in 4.2.0, where that file was greatly changed

**Comment by Ahmed-gubara** [comment]
Maybe it's too late, but if you have a `build.yaml` file then adding `- "pubspec.yaml"` to `source:` will fix this;
example:
```yaml
targets:
  $default:
    sources:
      include:
        - "pubspec.yaml"       # add this line
        - $package$
        - assets/**
        - assets/i18n/**
        - lib/**
        - swaggers/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "swaggers/"
          output_folder: "lib/swaggers/gen/"

```
