### ISSUE TITLE
Bad state: Unable to generate package graph

### ISSUE THREAD

**Issue by Aristidios** [FlutterGen/flutter_gen#275]
I get this error when I try to run ` flutter pub run build_runner build --delete-conflicting-outputs ` in my local package inside my project

```
Unhandled exception:
Bad state: Unable to generate package graph, no `/Users/user/bump/packages/bump_ui/.dart_tool/flutter_gen/pubspec.yaml` found.
#0      _pubspecForPath (package:build_runner_core/src/package_graph/package_graph.dart:232:5)
#1      _parsePackageDependencies (package:build_runner_core/src/package_graph/package_graph.dart:206:21)
#2      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:101:33)
<asynchronous suspension>
#3      main (file:///Users/user/Development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-2.1.11/bin/build_runner.dart:27:30)
<asynchronous suspension>
```

Here is my `pubspec.yaml `

```

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/discovery/
    - assets/images/welcome/
  fonts:
    - family: Circular Air Pro
      fonts:
        - asset: fonts/CircularAirPro-Black.otf
          weight: 900
        - asset: fonts/CircularAirPro-BlackItalic.otf
          weight: 900
          style: italic
        - asset: fonts/CircularAirPro-Bold.otf
          weight: 700
        - asset: fonts/CircularAirPro-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/CircularAirPro-Medium.otf
          weight: 500
        - asset: fonts/CircularAirPro-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/CircularAirPro-Book.otf
          weight: 400
        - asset: fonts/CircularAirPro-BookItalic.otf
          weight: 400
          style: italic
        - asset: fonts/CircularAirPro-Light.otf
          weight: 300
        - asset: fonts/CircularAirPro-LightItalic.otf
          weight: 300
          style: italic

flutter_gen:
  line_length: 80
  assets:
    package_parameter_enabled: true
```
