### ISSUE TITLE
[Feature Request] Support defining a "part-of" directive

### ISSUE THREAD

**Issue by danielmahon** [FlutterGen/flutter_gen#277]
I would like to add the generated files to be "part of" my constants file. I can add the `part "colors.gen.dart"` part but I am missing the corresponding `part of "constants.dart"` in the generated file. Could be configured as a pubspec option.

```yml
flutter_gen:
  # Optional
  output: lib/constants
  part_of_directive: constants.dart
```
