### ISSUE TITLE
[BUG]: TEST

### ISSUE THREAD

**Issue by wasabeef** [FlutterGen/flutter_gen#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.0.0

### Command type

build_runner (Default)

### What happened?

A bug happened!

### Relevant a pubspec.yaml.

```yaml
name: test

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80   # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true

flutter:
  assets:
    - assets/images
    - assets/images/chip3/chip3.jpg
    - assets/images/chip3/chip3.jpg # duplicated
    - assets/images/chip4/
    - assets/images/icons/fuchsia.svg
    - assets/images/icons/kmm.svg
    - assets/images/icons/paint.svg
    - assets/images/icons/dart@test.svg
    - assets/json/fruits.json
    - pictures/chip5.jpg
    - assets/flare/
    - assets/movie/
    - assets/unknown/unknown_mime_type.bk
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
