### ISSUE TITLE
[BUG]: Bug when using with flutter_localizations

### ISSUE THREAD

**Issue by tyypgzl** [FlutterGen/flutter_gen#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.0.1

### Command type

Dart command

### What happened?

It gives an error when used with flutter_localizations. Because the flutter_localizations package also generates under the flutter_gen folder.
```dart
"import 'package:flutter_gen/gen_l10n/app_localizations.dart';
```
It is necessary to use this import with flutter_localizations. 

### Relevant a pubspec.yaml.

```yaml
flutter_gen:
  output: lib/config/assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
```

### Relevant log output

```shell
-> fvm flutter gen-l10n
//Error Log
Because l10n.yaml exists, the options defined there will be used instead.
To use the command line arguments, delete the l10n.yaml file in the Flutter project.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
