### ISSUE TITLE
[BUG]: Internatiolization + no synthetic packages breaks build runner

### ISSUE THREAD

**Issue by slaci** [FlutterGen/flutter_gen#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.1.0+1

### Command type

build_runner (Default)

### What happened?

Following the [Internationalizing Flutter apps](https://docs.flutter.dev/development/accessibility-and-localization/internationalization) they recommed using the `flutter gen-l10n` command to generate files, which I assume this package provides or at least somehow it seems to be related.

For that to work it is possible to create an `l10n.yaml` which can contain the command's options. So I define the `synthetic-package: false` option, because otherwise the tool generates my files under `.dart_tools/flutter_gen` which is excluded source in Android Stuido by default, so I don't get any autocomplete.

The problem is, if I delete the `.dart_tools` folder, eg by `flutter clean` and run the `flutter gen-l10n` command with the `synthetic-package: false` option, then running `flutter pub run build_runner build` after will throw an error:

```
Bad state: Unable to generate package graph, no `C:\projectdir\.dart_tool\flutter_gen\pubspec.yaml` found.
#1      _parsePackageDependencies (package:build_runner_core/src/package_graph/package_graph.dart:206:21)
#2      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:101:33)
<asynchronous suspension>
#3      main (file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-2.3.2/bin/build_runner.dart:27:30)
```

Without `synthetic_packages` the command generates the translation files + the pubspec into `.dart_tools/flutter_gen`, but without `synthetic_packages` I only get my translation files into the output_dir, but no pubspec.

Sadly I cannot override options, as for weird reasons command line options don't work when the config file is there, so I cant run the command once with synthetic packages and once without:

> To use the command line arguments, delete the l10n.yaml file in the Flutter project.

I use build runner for different things (eg Go router) so it would be good if I could just ignore that error somehow. Any ideas why is this hapenning?

### Relevant a pubspec.yaml.

```yaml
name: Test
description: Test
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  formz: ^0.4.1
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.11
  go_router: ^5.1.3
  flutter_secure_storage: ^6.1.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  build_runner: ^2.0.0
  go_router_builder: ^1.0.0

flutter:
  generate: true
```

### Relevant log output

```shell
Bad state: Unable to generate package graph, no `C:\projectdir\.dart_tool\flutter_gen\pubspec.yaml` found.
#1      _parsePackageDependencies (package:build_runner_core/src/package_graph/package_graph.dart:206:21)
#2      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:101:33)
<asynchronous suspension>
#3      main (file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-2.3.2/bin/build_runner.dart:27:30)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
