### ISSUE TITLE
[BUG]: Cannot generate colors

### ISSUE THREAD

**Issue by DJTB** [FlutterGen/flutter_gen#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.1.0+1

### Command type

build_runner (Default)

### What happened?

First time checking out this package.

Attempting to run with the following colors file (taken from the example dir)
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="white">#FFFFFF</color>
    <color name="black">#000000</color>
    <color name="gray_70">#EEEEEE</color>
    <color name="gray_410">#979797</color>
    <color name="crimson_red" type="material">#CF2A2A</color>
    <color name="yellow_ocher" type="material material-accent">#DF9527</color>
</resources>
```
throws
```sh
Unhandled exception:
FormatException: Invalid radix-16 number (at line 2, character 2)
```  

Not sure what I'm doing wrong here or if it's a legitimate bug 🤷 

### Relevant a pubspec.yaml.

```yaml
name: theme_x
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: 3.3.8

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true # Include the Material Icons font

  # Assets for the application
  assets:
    - assets/audio/
    - assets/images/
    - assets/text/
    - assets/translations/

  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/Graphik-Regular.otf
          weight: 400
        - asset: assets/fonts/Graphik-Medium.otf
          weight: 500
        - asset: assets/fonts/Graphik-Semibold.otf
          weight: 600
    - family: Boing
      fonts:
        - asset: assets/fonts/Boing-Medium.ttf
          weight: 500
    - family: Icons
      fonts:
        - asset: assets/fonts/Stile_X_Icons.ttf
```

### Relevant log output

```shell
FlutterGen v5.1.0+1 Loading ... theme_x/pubspec.yaml
Unhandled exception:
FormatException: Invalid radix-16 number (at line 2, character 2)

 ^

#0      int._handleFormatError (dart:core-patch/integers_patch.dart:131)
#1      int._parse (dart:core-patch/integers_patch.dart:72)
#2      int.parse (dart:core-patch/integers_patch.dart:65)
#3      new HexColor (package:color/hex_color.dart:18)
#4      swatchFromPrimaryHex (package:flutter_gen_core/utils/color.dart:20)
#5      _colorStatement (package:flutter_gen_core/generators/colors_generator.dart:64)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#7      ListIterable.forEach (dart:_internal/iterable.dart:39)
#8      generateColors (package:flutter_gen_core/generators/colors_generator.dart:55)
#9      FlutterGenerator.build (package:flutter_gen_core/flutter_generator.dart:53)
#10     main (file:///Users/runner/work/flutter_gen/flutter_gen/packages/command/bin/flutter_gen_command.dart:48)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
