### ISSUE TITLE
[BUG]: Fails to generate any output with "source could not be parsed" error

### ISSUE THREAD

**Issue by johnwiese-ms** [FlutterGen/flutter_gen#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.1.0+1

### Command type

build_runner (Default)

### What happened?

I receive the provided output when I ran the below command:

`flutter packages pub run build_runner build --delete-conflicting-outputs`


### Relevant a pubspec.yaml.

```yaml
name: my_app
description: A new Flutter project.

publish_to: "none"

version: 4.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launch_icon.png"

  # flutter pub run flutter_launcher_icons:main
  adaptive_icon_background: "#3578CC"

flutter_native_splash:
  color: "#3578CC"

  image: assets/logo_small.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/regions_indv/
    - assets/onboarding/
    - assets/affiliations/
    - assets/referee_signals/

  fonts:
    - family: VolleyballParentIcons
      fonts:
        - asset: fonts/VolleyballParentIcons.ttf
```


### Relevant log output

```shell
[SEVERE] flutter_gen_runner on $package$:

Could not format because the source could not be parsed:

line 110, column 29 of .: 'in' can't be used as an identifier because it's a keyword.
    ╷
110 │           AssetGenImage get in => const AssetGenImage('assets/referee_signals/in.png');
    │                             ^^
    ╵
line 164, column 242 of .: 'in' can't be used as an identifier because it's a keyword.
    ╷
164 │   List<AssetGenImage> get values => [attackFault, authorizationToServe1, authorizationToServe2, ballIn, ballOut, ballTouch, cover, delayInService, delayRed, delayYellow, disqualification, double, endOfSet, expulsion, fourHits, illegalBlock, in, infraction, lift, lift2, lineViolation, misconductRed, misconductYellow, net, obstructedView, out, outOfRotation, point, reachingBeyondNet, replay, sideout, substitution, timeout1, touch];
    │                                                                                                            
                                                                                                                 
                     ^^
    ╵
[INFO] Running build completed, took 207ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 45ms

[SEVERE] Failed after 262ms
pub finished with exit code 1
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
