### ISSUE TITLE
[BUG]: Version 5.1.0+1 is incompatible with flutter_svg ^2.0.0+1

### ISSUE THREAD

**Issue by jayjah** [FlutterGen/flutter_gen#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.1.0+1

### Command type

build_runner (Default)

### What happened?

Current version of `flutter_gen_runner` is incompatible with the new version of `flutter_svg`: 2.0.0+1. 
See log output for details. 

### Relevant a pubspec.yaml.

```yaml
flutter_gen:
  output: lib/src/assets/
  line_length: 80

  integrations:
    flutter_svg: true
  assets:
    enabled: true
  fonts:
    enabled: true
```

### Relevant log output

```shell
lib/src/assets/assets.gen.dart:385:14: Error: The argument type 'SvgTheme?' can't be assigned to the parameter type 'SvgTheme' because 'SvgTheme?' is nullable and 'SvgTheme' isn't.
 - 'SvgTheme' is from 'package:vector_graphics_compiler/src/svg/theme.dart' ('../../.pub-cache/hosted/pub.dev/vector_graphics_compiler-1.0.1/lib/src/svg/theme.dart').
      theme: theme,
             ^
Target kernel_snapshot failed: Exception
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
