### ISSUE TITLE
[BUG]: no named parameter colorFilter when running app

### ISSUE THREAD

**Issue by kuyazee** [FlutterGen/flutter_gen#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

^5.2.0

### Command type

build_runner (Default)

### What happened?

I'm using flutter_gen with flutter_svg

The latest build seems to be incompatible with flutter_svg

### Relevant a pubspec.yaml.

```yaml
name: asdasdasd
description: asdasd

version: 3.0.0+22112100
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_gen: ^5.1.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/l10n/
    - assets/env/
    - assets/icons/
    - assets/google_fonts/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
```

### Relevant log output

```shell
: Error: No named parameter with the name 'colorFilter'.
assets.gen.dart:636
          colorFilter: colorFilter,
          ^^^^^^^^^^^
: Context: Found this candidate, but the arguments don't match.
svg.dart:329
      SvgPicture.asset(
      ^^^^^^^^^^^^^^^^
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
