### ISSUE TITLE
[BUG]: Unable to build project when sub-package is used

### ISSUE THREAD

**Issue by dhirajhimani** [FlutterGen/flutter_gen#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.2.0

### Command type

build_runner (Default)

### What happened?

Create a sub-package in the main project:- flutter create --template=package demo

After adding the entry in the pubspec.yaml, for the local package, the build_runner doesn't work, but if the flutter_gen is removed, it works. 

### Relevant a pubspec.yaml.

```yaml
name: app


dependencies:
   demo:
    path: demo/
  flutter:
    sdk: flutter


dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen: ^5.2.0
  flutter_gen_runner: ^5.2.0

flutter_gen:
  output: lib/app/generated/
  integration:
    flutter_svg: true

import_sorter:
  ignored_files:
    - \/lib\/*.g.dart
    - \/lib\/*.freezed.dart
    - \/lib\/*.config.dart
    - \/lib\/*.chopper.dart
    - \/lib\/*.mocks.dart

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/env/
```

### Relevant log output

```shell
The pubspec.lock file has changed since the .dart_tool/package_config.json file was generated, please run "flutter pub get" again.
pub finished with exit code 65
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Raviteja11122** [comment]
Any update on this issue?

**Comment by egyleader** [comment]
me too facing this issue on futter 3.7.10

**Comment by wasabeef** [comment]
Pleases `flutter_gen: ^5.2.0` remove it!

**Comment by dhirajhimani** [comment]
But it gives following error 

`  Bad state: Unable to generate package graph, no  'dart_tool/flutter_gen/pubspec.yaml' found. `

**Comment by egyleader** [comment]
## Temp workaround 

this is a temp workaround to continue development with this package until this issue is fixed :

1. comment all the sub-packages in pubspec.yaml
2. add   the required packages & configuration for fluttergen
```yaml
dev_dependencies:
  flutter_gen: ^5.3.0
  flutter_gen_runner: ^5.3.0
   build_runner: ^2.2.0

flutter_gen:
  output: lib/generated/assets
  integrations:
    flutter_svg: true
```
3. run the build command `flutter pub run build_runner build --delete-conflicting-outputs`
this will generate all the assets code .

4.  comment the fluttergen packages & configuration  and uncomment the subpackages 
this is to avoid build conflicts with other code generation & use sub packages.
