### ISSUE TITLE
[FR]:  Customize Assets class name

### ISSUE THREAD

**Issue by gbmiranda** [FlutterGen/flutter_gen#395]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the problem

I have a design system package with icons shared across multiple projects.

For each project, I need unique icons.

### Describe the solution

The idea would be to customize the generated Assets class, for example:

**DesignSystemAssets** and **MyAppAssets**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexV525** [comment]
```yaml
flutter_gen:
  assets:
    outputs:
      class_name: CustomNameAssets
```
