### ISSUE TITLE
[BUG]: analyzer v6 is not supported

### ISSUE THREAD

**Issue by koji-1009** [FlutterGen/flutter_gen#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.3.1

### Command type

build_runner (Default)

### What happened?

If I add a library that requires analyzer v6 (e.g. [riverpod_lint v2](https://pub.dev/packages/riverpod_lint/changelog#200---2023-08-03)) to my application, pub get fails.

### Relevant a pubspec.yaml.

```yaml
name: app

dev_dependencies:
  riverpod_lint: ^2.0.0
  flutter_gen_runner: ^5.0.0

flutter_gen:
  integrations:
    flutter_svg: true
```

### Relevant log output

```shell
/Users/koji/fvm/versions/beta/bin/flutter --no-color pub upgrade
Waiting for another flutter command to release the startup lock...
Resolving dependencies...
Because flutter_gen_runner >=5.3.0 <5.3.1 depends on flutter_gen_core 5.3.0 and flutter_gen_runner >=5.2.0 <5.3.0 depends on flutter_gen_core 5.2.0, flutter_gen_runner >=5.2.0 <5.3.1 requires flutter_gen_core 5.2.0 or 5.3.0.
And because flutter_gen_runner >=5.1.0+1 <5.2.0 depends on flutter_gen_core 5.1.0+1 and flutter_gen_runner >=5.1.0 <5.1.0+1 depends on flutter_gen_core 5.1.0, flutter_gen_runner >=5.1.0 <5.3.1 requires flutter_gen_core 5.1.0 or 5.1.0+1 or 5.2.0 or 5.3.0.
And because flutter_gen_runner >=5.0.3 <5.1.0 depends on flutter_gen_core 5.0.3 and flutter_gen_runner >=5.0.2 <5.0.3 depends on flutter_gen_core 5.0.2, flutter_gen_runner >=5.0.2 <5.3.1 requires flutter_gen_core 5.0.2 or 5.0.3 or 5.1.0 or 5.1.0+1 or 5.2.0 or 5.3.0.
And because flutter_gen_runner >=5.0.1 <5.0.2 depends on flutter_gen_core 5.0.1 and flutter_gen_runner >=5.0.0 <5.0.1 depends on flutter_gen_core 5.0.0, flutter_gen_runner >=5.0.0 <5.3.1 requires flutter_gen_core 5.0.0 or 5.0.1 or 5.0.2 or 5.0.3 or 5.1.0 or 5.1.0+1 or 5.2.0 or 5.3.0.
And because flutter_gen_core >=4.2.0 <5.0.1 depends on analyzer >=2.0.0 <5.0.0 and flutter_gen_runner >=5.3.1 depends on flutter_gen_core 5.3.1, flutter_gen_runner >=5.0.0 requires analyzer >=2.0.0 <5.0.0 or flutter_gen_core 5.0.1 or 5.0.2 or 5.0.3 or 5.1.0 or 5.1.0+1 or 5.2.0 or 5.3.0 or 5.3.1.
And because flutter_gen_core >=5.0.1 depends on analyzer >=4.7.0 <6.0.0 and riverpod_lint >=2.0.0 depends on analyzer ^6.0.0, riverpod_lint >=2.0.0 is incompatible with flutter_gen_runner >=5.0.0.
So, because conference_2023 depends on both riverpod_lint ^2.0.0 and flutter_gen_runner ^5.0.0, version solving failed.
Process finished with exit code 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by koji-1009** [comment]
Maybe this issue will be fixed by #409.

**Comment by lailai0715** [comment]
Any update on this?

**Comment by foxanna** [comment]
This problem prevents upgrading to the latest versions of other code-generating dependencies like `freezed`, `json_serializable`, `retrofit` without significant effort. @wasabeef, any chance you could look at https://github.com/FlutterGen/flutter_gen/pull/407? Thanks in advance!

**Comment by noga-dev** [comment]
Use this for now

```yaml
dependency_overrides:
  flutter_gen_core:
    git:
      url: https://github.com/FlutterGen/flutter_gen.git
      ref: 8c57b5aa73f7793d614f064ec8e00434cc4cf01a
      path: packages/core
```
