### ISSUE TITLE
[BUG]: The class 'FileSystemEvent' can't be extended

### ISSUE THREAD

**Issue by subzero911** [FlutterGen/flutter_gen#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

3.1.5

### Command type

build_runner (Default)

### What happened?

Something happened, and now I always get an error, trying to build assets.

### Relevant a pubspec.yaml.

```yaml
name: goldy
description: Children task tracker.

publish_to: 'none'

version: 1.0.0+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  avatar_stack: ^1.1.2
  cached_network_image: ^3.2.3
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.8
  dynamic_height_grid_view: ^0.0.3
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_flavor: ^3.1.3
  flutter_inappwebview: ^5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.1.1
  flutter_multi_formatter: ^2.10.2
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  flutter_top_blocked_bouncing_scroll_physics: ^1.0.0
  fluttertoast: ^8.2.2
  fresh_graphql: ^0.5.2
  get_it: ^7.6.0
  go_router: ^7.1.1
  gql_http_link: ^1.0.1
  graphql: ^5.2.0-beta.4
  graphql_codegen: ^0.13.4
  graphql_flutter: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  infinite_listview: ^1.1.0 # двунаправленный список; используется в календаре
  intl: ^0.18.0
  json_annotation: ^4.8.1
  just_the_tooltip: ^0.0.12
  local_auth: ^2.1.5
  local_auth_android: ^1.0.19
  local_auth_ios: ^1.0.13
  logger: ^1.2.2
  mobx: ^2.2.1
  mts_granat:
    path: packages/mts_granat
  network_info_plus: ^4.1.0
  page_view_dot_indicator: ^2.3.0
  pin_code_fields:
    git:
      url: https://github.com/adar2378/pin_code_fields.git
      ref: master
  quiver: ^3.2.1
  #  sdk_sso_flutter:
  #    git:
  #      url: https://gitlab.services.mts.ru/goldy/SDKSSO.git
  #      ref: master
  share_plus: ^7.2.1
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  slang: ^3.11.1
  slang_flutter: ^3.11.0
  time: ^2.1.3
  url_launcher: ^6.1.14
  very_good_infinite_list: ^0.7.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  json_serializable_mobx: ^0.10.3
  melos: ^3.2.0
  mobx_codegen: ^2.3.0

dependency_overrides:
  collection: ^1.17.2 # flutter_test опирается на 1.17.1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
  # colors:
  #   inputs:
  #     - assets/color/colors.xml
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/wallet/
    - assets/images/wallet/card_logos/
    - assets/images/wallet/coins_exchange_statuses/
    - assets/images/mascot/
    - assets/icons/
    - assets/icons/new_task/
    - assets/icons/task_details/
    - assets/icons/nav_bar/
    - assets/icons/rewards/
    - assets/icons/wallet/
    - assets/icons/task_sample/
```

### Relevant log output

```shell
svmolchan1@0000NBB0TX4DJ20 goldy % fluttergen     
Can't load Kernel binary: Invalid kernel binary format version.
Building package executable... 
Failed to build flutter_gen:flutter_gen_command:
../../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {
                                                        ^
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
