### ISSUE TITLE
[BUG]: Why some json file doen't convert to LottieGenImage?

### ISSUE THREAD

**Issue by flexboni** [FlutterGen/flutter_gen#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.4.0

### Command type

build_runner (Default)

### What happened?

(My english is not good...im so sorry)

Some files doen't convert to LottieGenImage.
Some files covert well but a few things not good.
How can i check??
![image](https://github.com/FlutterGen/flutter_gen/assets/29271126/d75a09e6-f4d3-4b95-b0a1-20423fb59ec3)

### Relevant a pubspec.yaml.

```yaml
name: mid_cave
description: mid_cave

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  amazon_cognito_identity_dart_2: ^3.6.0
  animated_text_kit: ^4.2.2
  bottom_sheet: ^4.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  chewie: ^1.4.0
  circular_countdown_timer: ^0.2.3
  coast: ^2.0.2
  collection: ^1.18.0
  colorful_safe_area: ^1.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  drag_and_drop_lists: ^0.3.3
  entry: ^0.0.9
  expandable: ^5.0.1
  fl_chart:
    git: https://github.com/frybitsinc/fl_chart_gradient.git
  flex_color_picker: ^3.3.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_debouncer: ^2.0.0
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.1.1
  flutter_gen: ^5.4.0
  flutter_html: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  flutter_math_fork: ^0.7.1
  flutter_riverpod: ^2.4.1
  flutter_screenutil: ^5.8.4
  flutter_slidable: ^3.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  flutter_tex: ^4.0.5
  flutter_tts: ^3.8.2
  flutter_typeahead: ^4.8.0
  flutter_widget_from_html_core: null
  fluttertoast: ^8.2.2
  form_builder_validators: ^9.1.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  fwfh_svg: ^0.8.0+3
  get: ^4.6.5
  go_router: ^13.0.0
  graphview: ^1.2.0
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.1
  jiffy: ^6.2.1
  json_annotation: ^4.8.1
  just_audio: ^0.9.35
  logger: ^2.0.2+1
  lottie: ^2.6.0
  math_expressions: ^2.4.0
  math_keyboard: ^0.2.1
  multi_split_view: ^2.4.0
  new_version_plus: ^0.0.11
  overlay_tooltip: ^0.2.3
  path_provider: ^2.1.0
  pencil_kit:
    git: https://github.com/frybitsinc/flutter-pencilkit.git
  perfect_volume_control: ^1.0.5
  pinput: ^2.2.31
  provider: ^6.0.5
  riverpod_annotation: ^2.3.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  signature: ^5.3.0
  super_tooltip: ^2.0.5
  table_calendar: ^3.0.9
  timelines: ^0.1.0
  touchable: ^1.0.2
  typewritertext: ^1.9.0
  uuid: ^4.2.2
  vertical_scroll_tabbar_icon:
    git:
      url: https://github.com/frybitsinc/vertical_scroll_tabbar_icon.git
      ref: main
  video_player: ^2.6.0
  widget_and_text_animator: ^1.1.5
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter_gen:
  integrations:
    lottie: true
    flutter_svg: true

flutter:
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/icons/curriculum/
    - assets/icons/app_bar/
    - assets/icons/side_bar/
    - assets/icons/home/
    - assets/icons/grade/
    - assets/image_sequences/
    - assets/image_sequences/migo_loop/
    - assets/image_sequences/map/
    - assets/image_sequences/psrj_BG_loop_alpha_DeMain/
    - assets/images/
    - assets/images/vls/
    - assets/images/coachmark/
    - assets/images/curriculum/
    - assets/images/exam/
    - assets/images/home/
    - assets/images/home/big_units/
    - assets/images/home/bookmark/
    - assets/images/league/
    - assets/images/my_page/
    - assets/images/my_page/point_mall/
    - assets/images/point_mall/
    - assets/images/onboarding/
    - assets/images/onboarding/textbook/
    - assets/images/onboarding/workbook/
    - assets/images/practice/
    - assets/images/pre_test/
    - assets/images/pre_test/
    - assets/images/review/
    - assets/json/
    - assets/sounds/
    - assets/sounds/vls/
    - assets/sounds/scripts/
    - assets/sounds/scripts/hyonujeans/
    - assets/sounds/scripts/jang_daniels/
    - assets/videos/
    - assets/fonts/

  uses-material-design: true

  fonts:
    - family: NanumMyeongjo
      fonts:
        - asset: assets/fonts/NanumMyeongjo.ttf
    - family: KaTeX_Main
      fonts:
        - asset: assets/fonts/KaTeX_Main-Regular.ttf
    - family: KaTeX_Main_Italic
      fonts:
        - asset: assets/fonts/KaTeX_Main-Italic.ttf
    - family: LatinModern
      fonts:
        - asset: assets/fonts/latinmodern-math.otf
    - family: PretendardBold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
    - family: PretendardLight
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf
    - family: PretendardMedium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
    - family: MidCustomIcons
      fonts:
        - asset: assets/fonts/MidCustomIcons.ttf
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
