### ISSUE TITLE
[FR]: Parsing colors into several separate classes.

### ISSUE THREAD

**Issue by filippkos** [FlutterGen/flutter_gen#481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I want to create a color structure more complex than one class with many fields inside. At least, I would like to be able to parse one or more xml files into several classes. It is possible to specify only one output class name. I didn't find such an option in the documentation.

```yaml
# podspec.yaml
  colors:
    enabled: true
    outputs:
      class_name: CustomColors
    inputs:
      - assets/custom_colors.xml
      - assets/other_custom_colors.xml
```

### Describe the solution

You can do it, for example, so that each xml file is parsed into a separate class.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
