### ISSUE TITLE
Name collision with flutter localization when using build_runner.

### ISSUE THREAD

**Issue by Nico04** [FlutterGen/flutter_gen#49]
This package has the exact same name than the [official flutter localization package](https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit), resulting in name collision.

After importing flutter_gen package (this package), my localization files are broken.
`error: Target of URI doesn't exist: 'package:flutter_gen/gen_l10n/app_localizations.dart'.`

Any ideas ?

**EDIT**
I just found that the file "\.dart_tool\package_config.json" contains a ref to flutter_gen-1.2.1

```
    {
      "name": "flutter_gen",
      "rootUri": "../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_gen-1.2.1",
      "packageUri": "lib",
      "languageVersion": "2.7"
    },
```

And this package is currently at 1.2.1, so I guess the plugin used by Flutter is this one ? So it's the same package after all ?
But why it collides then ?

**Comment by Nico04** [comment]
A temp workaround is to comment `flutter_gen` in `dev_dependencies` after the files are generated, and git track them.

```
dev_dependencies:
  build_runner: ^1.10.4
  json_serializable: ^3.5.0
  # flutter_gen: ^1.2.1
```

**Comment by wasabeef** [comment]
@Nico04 
Thank you so much.

I'm aware of this issue.
Can you use [Dart CLI](https://github.com/FlutterGen/flutter_gen#using-a-dart-command-line) or [Homebrew](https://github.com/FlutterGen/flutter_gen#using-a-homebrew-formula) instead of build_runner until it's resolved?

**Comment by wasabeef** [comment]
@Nico04 

@EmanueleVinci 
I'm sorry for the late reply.

Just now we released `v3.0.2` null safety so could you try it?

- Null Safety
- Rename package for build_runner

```yaml
flutter_gen:
  null_safety: true # Optional (default: true)

dev_dependencies:
  build_runner: 
  flutter_gen_runner: ^3.0.2 # Since v2, renamed
```
