### ISSUE TITLE
[BUG]: Method *AssetBytesLoader* and *SvgAssetLoader* not found

### ISSUE THREAD

**Issue by agnamc9** [FlutterGen/flutter_gen#535]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Command type

build_runner (Default)

### What happened?

Hello. Thank you for this great library. After launching ```flutter pub run build_runner build```, I encountered the generated method below with some undefined methods.

<img width="666" alt="Screenshot 2024-06-26 at 15 17 40" src="https://github.com/FlutterGen/flutter_gen/assets/4026625/b9fa9dc6-d204-429c-a796-30d3dd0fd275">

### Relevant a pubspec.yaml.

```yaml
---
name: app
description: A new Flutter project.
publish_to: none
version: 2.0.16+67
environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  amplify_auth_cognito: ^0.4.0
  amplify_flutter: ^0.4.0
  amplify_storage_s3: ^0.4.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  clipboard: ^0.1.3
  collection: ^1.15.0
  contacts_service: ^0.6.3
  dio: ^4.0.0
  event_bus: ^2.0.0
  file_picker: ^5.3.0
  firebase_core: ^2.28.0
  firebase_dynamic_links: ^5.5.0
  flavor: ^2.0.0
  flutter:
    sdk: flutter
  flutter_face_api: 5.2.2
  flutter_face_core: 5.2.0
  flutter_image_compress: ^1.1.0
  flutter_jailbreak_detection: ^1.8.0
  flutter_localizations:
    sdk: flutter
  flutter_phone_direct_caller: ^2.0.0
  flutter_riverpod: ^1.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^1.0.3
  google_maps_flutter: ^2.0.9
  image_cropper: ^1.5.1
  image_picker: ^0.8.4+3
  intl: ^0.19.0
  local_auth: ^2.1.6
  location: ^4.3.0
  lottie: ^1.2.1
  mask_text_input_formatter: ^2.0.0
  ndialog: ^4.1.0
  objectbox: ^2.2.1
  objectbox_flutter_libs: any
  onesignal_flutter: ^3.5.0
  path: null
  path_provider: null
  permission_handler: ^8.2.5
  pretty_dio_logger: ^1.2.0-beta-1
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  retrofit: any
  notification_permissions: ^0.6.1
  super_tooltip: ^2.0.4
  get_storage: ^2.1.1
  share_plus: ^2.0.4
  pinput: ^1.2.0
  sizer: ^2.0.13
  url_launcher: ^6.0.9
  very_good_infinite_list: ^0.4.0
  encrypt: ^5.0.1
  upgrader: ^6.5.0
  package_info_plus: ^4.0.1
  calendar_date_picker2: ^1.1.5
  shimmer: ^2.0.0
  currency_text_input_formatter: ^2.2.3
  autocomplete_textfield: ^2.0.1
  flutter_emoji: ^2.4.0
  custom_info_window: ^1.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  percent_indicator: ^4.2.2
  geocoding: ^2.1.0
  story_view: ^0.16.0
  pin_code_fields: ^8.0.1

  custom_refresh_indicator: ^2.2.1
  fluttercontactpicker: ^4.7.0
  money_formatter: ^0.0.4
  page_route_animator:
  rive: ^0.8.4
  open_file_plus: ^3.4.1
  firebase_crashlytics: ^3.5.0
  external_app_launcher: ^3.1.0
  open_settings: ^2.0.2
  fluttertoast: ^8.2.4
  screen_protector: ^1.4.2
  fl_chart: ^0.67.0
  vector_graphics:

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  dart_code_linter: ^1.1.1
  dart_code_metrics: ^5.7.6
  flutter_launcher_icons: "^0.9.1"
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  objectbox_generator: any
  retrofit_generator: any


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/licenses/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_medium.ttf
          weight: 300
        - asset: assets/fonts/metropolis_regular.otf
          weight: 400
        - asset: assets/fonts/avenir_heavy.ttf
          weight: 600
        - asset: assets/fonts/avenir_light.ttf
          weight: 200
        - asset: assets/fonts/avenir_black.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins_regular.ttf
          weight: 400
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_semibold.ttf
          weight: 600
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
    - family: CourierNew
      fonts:
        - asset: assets/fonts/cour.ttf

flutter_gen:
  integrations:
    flutter_svg: true
```

### Relevant log output

```shell
lib/gen/assets.gen.dart:2179:13: Error: The method 'AssetBytesLoader' isn't defined for the class 'SvgGenImage'.
 - 'SvgGenImage' is from 'package:app/gen/assets.gen.dart' ('lib/gen/assets.gen.dart').
Try correcting the name to the name of an existing method, or defining a method named 'AssetBytesLoader'.
          ? AssetBytesLoader(_assetName,
            ^^^^^^^^^^^^^^^^
lib/gen/assets.gen.dart:2181:13: Error: The method 'SvgAssetLoader' isn't defined for the class 'SvgGenImage'.
 - 'SvgGenImage' is from 'package:app/gen/assets.gen.dart' ('lib/gen/assets.gen.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SvgAssetLoader'.
          : SvgAssetLoader(_assetName,
            ^^^^^^^^^^^^^^
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
