### ISSUE TITLE
[BUG]: Import conflict: Image class defined in flutter and rive

### ISSUE THREAD

**Issue by codeOfJannik** [FlutterGen/flutter_gen#545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.6.0

### Command type

build_runner (Default)

### What happened?

Out of nowhere we started to get an error in the generated file that a image class is found both in `package/flutter/...widgets.dart` and `package/rive`:
`The name 'Image' is defined in the libraries 'package:flutter/src/widgets/image.dart (via package:flutter/widgets.dart)' and 'package:rive/src/rive_core/shapes/image.dart (via package:rive/rive.dart)'.`

Anyone else already faced that issue? Has anything changed in the package?
Or did something change in rive, e.g. they started to export the image class so it's visible?

A workaround for now is to add a `hide Image` to the rive import manually after the `assets.gen.dart` file has been generated.

Our assets folder contains png, jpg, svg and riv files.

### Relevant a pubspec.yaml.

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  rive: ^0.13.12

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/images/first_time_ux/
    - assets/images/first_time_ux/alerting/de/
    - assets/images/first_time_ux/alerting/en/
    - assets/images/group/
    - assets/images/menu_icons/


flutter_gen:
  output: lib/src/generated/
  line_length: 180
  assets:
    outputs:
      package_parameter_enabled: true

  integrations:
    flutter_svg: true
    rive: true
```

### Relevant log output

```shell
FlutterGen v5.6.0 Loading ... pubspec.yaml
[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 903ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Deleting 1 declared outputs which already existed on disk.
[INFO] Checking for unexpected pre-existing outputs. completed, took 2ms

[INFO] Running build...
Generated: lib/src/generated/assets.gen.dart
FlutterGen finished.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mhammerc** [comment]
Hello,

The error appears starting with `rive` version `0.13.10`.

Version `0.13.9` doesn't export `Image`.

**Comment by AlexV525** [comment]
Sounds like a `rive` issue which means the issue should be reported to the `rive` package?

**Comment by codeOfJannik** [comment]
Why? If the rive package needs to export the image class they can do that. The flutter_gen rive import statement should be adjusted to hide Image from rive

**Comment by Sevastyan** [comment]
Not hide, but `flutter_gen` must have been using aliases for imports in the first place. Otherwise, the issue might return.

**Comment by AlexV525** [comment]
We have a relatively releasing procedure. If you're encountering the issue you can use the fix in the PR https://github.com/FlutterGen/flutter_gen/pull/548 by overriding dependencies.

**Comment by mhammerc** [comment]
> We have a relatively long releasing procedure. If you're encountering the issue you can use the fix in the PR #548 by overriding dependencies.

Hello,

Just wanted to say thank you for the upcoming fix and the ongoing support of `flutter_gen`. This is what makes the Flutter community thrive, and it helps many.

**Comment by msxenon** [comment]
its better to use import alias just like mockito generator)

**Comment by AlexV525** [comment]
The issue is closed because the fix has been shipped through the v5.7.0 version.

**Comment by usmanovrustam** [comment]
> The issue is closed because the fix has been shipped through the v5.7.0 version.

I am using v5.7.0 version. but there was the same issue

**Comment by AlexV525** [comment]
> > The issue is closed because the fix has been shipped through the v5.7.0 version.
> 
> I am using v5.7.0 version. but there was the same issue

Attach more details?

**Comment by usmanovrustam** [comment]
> > > The issue is closed because the fix has been shipped through the v5.7.0 version.
> > 
> > 
> > I am using v5.7.0 version. but there was the same issue
> 
> Attach more details?


these are my current dependencies: 
```

dependencies:
  flutter:
    sdk: flutter
  rive: 0.13.13
  flutter_svg: 2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  build_runner: 2.4.12
  flutter_gen_runner: 5.7.0
```
And this is the error : 

![Screenshot 2024-09-03 at 14 51 37](https://github.com/user-attachments/assets/7fdf00dd-97bb-431f-95da-4e09372cd91b)
