### ISSUE TITLE
[BUG]: ambigus import of `Image`class in generated `.gen.dart` file

### ISSUE THREAD

**Issue by yeikel16** [FlutterGen/flutter_gen#552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.6.0

### Command type

build_runner (Default)

### What happened?

When is generate a Rive asset exist two `Image` class, one from widget library and other from Rive library causing an ambiguous import.

![Captura de pantalla 2024-08-14 a la(s) 7 19 06 p m](https://github.com/user-attachments/assets/489c2e03-553a-4d8c-a934-d523ad4b83ec)

### Relevant a pubspec.yaml.

```yaml
name: example
description: A sample project using FlutterGen.
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  rive: ^0.13.12

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.0.0
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter

flutter_gen:
  integrations:
    flutter_svg: true
    rive: true

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/common/rive/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
