### ISSUE TITLE
[BUG]: Image class from Rive clashes with the Image widget from Flutter

### ISSUE THREAD

**Issue by mkobuolys** [FlutterGen/flutter_gen#556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.6.0

### Command type

build_runner (Default)

### What happened?

After upgrading the project to Flutter 3.24.0, a new error appeared with all the `AssetGenImage` assets:

`The element type 'dynamic' can't be assigned to the list type 'Widget'`

This error occurs because the Image class from Rive clashes with the Image widget from Flutter, thus the return type of AssetGenImage.image becomes dynamic (not sure which Image type to use).

The issue could be resolved by updating the rive import like (not sure if this a proper approach to this, though):

`import 'package:rive/rive.dart' hide Image;`

### Relevant a pubspec.yaml.

```yaml
dependencies:
  rive: ^0.13.12

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0

flutter_gen:
  output: lib/assets/gen

  integrations:
    flutter_svg: true
    rive: true

  assets:
    enabled: true
```

### Flutter doctor command result

```shell
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-LT)
    • Flutter version 3.24.0 on channel stable at /path/to/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2
```

### Relevant log output

```shell
The element type 'dynamic' can't be assigned to the list type 'Widget'. dart(list_element_type_not_assignable)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
