### ISSUE TITLE
[BUG]: Material image conflict with rive image on generated file

### ISSUE THREAD

**Issue by mohsinraza-fdev** [FlutterGen/flutter_gen#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.7.0

### Command type

build_runner (Default)

### What happened?

<img width="780" alt="image" src="https://github.com/user-attachments/assets/1f4e799f-d78d-45e9-81f8-62eb51ae087d">

Import conflict of Image class from Material and Rive, in the generated file

### Relevant a pubspec.yaml.

```yaml
name: digital_hire_mobile

flutter_gen:
  output: lib/assets_gen/
  line_length: 80

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/translations/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
