### ISSUE TITLE
[BUG]: Build warning when configuring flutter_gen using build.yaml

### ISSUE THREAD

**Issue by bartvanandel** [FlutterGen/flutter_gen#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.8.0

### Command type

build_runner (Default)

### What happened?

The Dart build chain emits a warning when using build.yaml to configure flutter_gen. Its mere presence triggers this warning. Ideally this should be fixed, but I don't think it currently causes any real problems. See log output below.

Relevant part of our build.config (pretty much following your example):

```yaml
targets:
  $default:
    builders:
      flutter_gen:
        # See: https://pub.dev/packages/flutter_gen#configuration-file
        options: 
          # output: lib/gen/ # Optional (default: lib/gen/)
          # line_length: 80 # Optional (default: 80)
          integrations:
            flutter_svg: true
```

### Relevant a pubspec.yaml.

```yaml
name: care
publish_to: 'none'
version: 1.0.0+1

environment:
  # Dart SDK version.
  # See https://dart.dev/go/sdk-constraint
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  ...
  flutter:
    sdk: flutter
  flutter_gen: ^5.8.0
  ...
  flutter_svg: ^2.0.10+1
  ...

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  ...

flutter:
  uses-material-design: true

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
```

### Relevant log output

```shell
[...]

Building package executable... 
Built build_runner:build_runner.
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 610ms

[WARNING] ApplyBuilders:
Configuring `flutter_gen:flutter_gen` in target `care:care` but this is not a known Builder
FlutterGen v5.8.0 Loading ...
Reading FlutterGen options from pubspec.yaml
Reading FlutterGen options from build.yaml
[INFO] BuildDefinition:Initializing inputs

[...]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexV525** [comment]
Can you try `flutter_gen_runner` as the builder's name?

**Comment by bartvanandel** [comment]
That clears the warning, but also stops loading the config:

```
...
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 558ms

FlutterGen v5.8.0 Loading ...
Reading FlutterGen options from pubspec.yaml
[INFO] BuildDefinition:Initializing inputs
...
```

**Comment by AlexV525** [comment]
@b2nkuu Do you want to be assigned to this?

**Comment by b2nkuu** [comment]
> @b2nkuu Do you want to be assigned to this?
ok, i do.

**Comment by BetterB0y** [comment]
I think on main it stills make warning. No matter flutter_gen_runner or flutter_gen

**Comment by AlexV525** [comment]
> I think on main it stills make warning. No matter flutter_gen_runner or flutter_gen

Could you provide your configuration?

**Comment by BetterB0y** [comment]
Pubspec
```
dependencies:
  flutter:
    sdk: flutter

  flutter_svg: 2.0.16


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.14
  flutter_gen_repository:
    git:
      url: https://github.com/FlutterGen/flutter_gen.git
      ref: 08127d1
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/sample.vec
  fonts:
    - family: NunitoSansVariableFont
      fonts:
        - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
        - asset: assets/fonts/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
          style: italic

```

build.yaml
```
targets:
  $default:
    builders:
      flutter_gen_runner: # or flutter_gen
        options:
          output: lib/core/ui/assets_gen
          line_length: 120
          integrations:
            flutter_svg: true

```

Console ouput
```
[WARNING] Configuring `flutter_gen_runner:flutter_gen_runner` in target `empty:empty` but this is not a known Builder
```
or
```
[WARNING] Configuring `flutter_gen:flutter_gen` in target `empty:empty` but this is not a known Builder
```
