### ISSUE TITLE
[FR]: Add package name to directory path

### ISSUE THREAD

**Issue by EndersonPro** [FlutterGen/flutter_gen#602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I'm generating assets from an internal package for an application, and I need to access the path of the folder where the assets are and I have enabled the `directory_path_enabled` flag, however I also have the `package_parameter_enabled` flag active. So I expected the asset path to also have the path.

Is that possible?

### Describe the solution

```yaml
flutter_gen:
  output: lib/generated/
  line_length: 80
  assets:
    outputs:
      directory_path_enabled: true
      package_parameter_enabled: true
```

Current result:
```dart
class $AssetsI18nGen {
  const $AssetsI18nGen();

  /// Directory path: assets/i18n
  String get path => 'assets/i18n';
}
```

Expected result:
```dart
class $AssetsI18nGen {
  const $AssetsI18nGen();

  /// Directory path: packages/my_package/assets/i18n
  String get path => 'packages/my_package/assets/i18n';
}
```

### Additional context

Assets config:
```yaml
flutter:
  assets:
    - assets/i18n/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
