### ISSUE TITLE
[BUG]: Package Dependency

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [FlutterGen/flutter_gen#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.8.0

### Command type

Dart command

### What happened?

i got this issue when run pub get 
Because flutter_gen_runner >=5.8.0 depends on flutter_gen_core 5.8.0 which depends on dart_style ^2.2.4, flutter_gen_runner >=5.8.0 requires dart_style ^2.2.4.
And because freezed 2.5.8 depends on dart_style ^3.0.1 and no versions of freezed match >2.5.8 <3.0.0, flutter_gen_runner >=5.8.0 is incompatible with freezed ^2.5.8.
So, because sayyo depends on both freezed ^2.5.8 and flutter_gen_runner ^5.8.0, version solving failed.

This seem like version of package dependency was outdated . 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pro100andrey** [comment]
Hi, Same issue
``` bash
➜  dart run build_runner build --delete-conflicting-outputs
Building package executable... 
Built build_runner:build_runner.
[INFO] Generating build script completed, took 185ms
[WARNING] ../../../../../../.pub-cache/hosted/pub.dev/flutter_gen_core-5.8.0/lib/flutter_generator.dart:34:36: Error: Required named parameter 'languageVersion' must be provided.
    final formatter = DartFormatter(pageWidth: lineLength, lineEnding: '\n');
                                   ^
../../../../../../.pub-cache/hosted/pub.dev/dart_style-3.0.1/lib/src/dart_formatter.dart:81:3: Context: Found this candidate, but the arguments don't match.
  DartFormatter(
```

**Comment by AlexV525** [comment]
Please use the main branch of the core which is compatible with dart_style v3.

**Comment by CaoGiaHieu-dev** [comment]
@AlexV525 did you have plan to deploy it ?

**Comment by AlexV525** [comment]
> @AlexV525 did you have plan to deploy it ?

I don't have the permission to publish new versions yet. I'm actively asked other members to do so but it might take a bit longer than expected.

**Comment by CaoGiaHieu-dev** [comment]
> Please use the main branch of the core which is compatible with dart_style v3.

workaroud by override this
```yaml
dependency_overrides:
  flutter_gen_core:
    git:
      url: https://github.com/FlutterGen/flutter_gen.git
      path: packages/core/
```

but it need to remove this. is it ok ?
```yaml
flutter_gen:
  generate: false // this should be remove
  assets:
    outputs:
      class_name: Assets
      style: camel-case
  integrations:
    flutter_svg: true
```
