### ISSUE TITLE
[BUG]: Need option to generate only String constants without AssetGenImage

### ISSUE THREAD

**Issue by houzixiashanxiedaima** [FlutterGen/flutter_gen#636]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

5.8.0

### Command type

build_runner (Default)

### Description
Currently, FlutterGen always generates `AssetGenImage` types for image assets. In our project, we need to use only String constants for asset paths (like `static const String imagesLogo = 'assets/images/logo.png'`) without the `AssetGenImage` wrapper class. This is particularly important for projects migrating from string-based asset references or maintaining compatibility with existing codebases.

### Current Behavior
```dart 
class Assets {
    static const AssetGenImage imagesLogo = AssetGenImage('assets/images/logo.png');
}
```

### Desired Behavior
```dart
class Assets {
    static const String imagesLogo = 'assets/images/logo.png';
}
```

### Relevant a pubspec.yaml.

```yaml
#资源文件生成配置
flutter_gen:
  output: lib/generated/ # 输出目录
  line_length: 80 # 行长度，过长时会自动换行
  
  integrations:
    flutter_svg: false   # 禁用 svg 集成
    flare_flutter: false # 禁用 flare 集成
    rive: false         # 禁用 rive 集成
    lottie: false       # 禁用 lottie 集成
    
  assets:
    outputs:
      class_name: Assets
      style: camel-case  # 使用驼峰命名
      package_parameter_enabled: false  # 不生成包参数

flutter:
  generate: false
  uses-material-design: true
  assets:
    - images/
    - images/2.0x/
    - images/3.0x/
    - audios/
    - assets/
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
