### ISSUE TITLE
[BUG]: Unrecognized keys: [flare_flutter]; supported keys: [image, flutter_svg, rive, lottie] when running build_runner with flutter_gen_runner 5.9.0

### ISSUE THREAD

**Issue by Thanhnq1608** [FlutterGen/flutter_gen#664]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

5.9.0

### Command type

build_runner (Default)

### What happened?

A bug occurred when I ran build_runner 2.4.13 with flutter_gen_runner 5.9.0, but it worked fine with version 5.8.0.

### Relevant a pubspec.yaml.

```yaml
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - images/
    - assets/icons/
    - assets/icons/setting/
```

### Relevant log output

```shell
"You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


CheckedFromJsonException
Could not create `FlutterGenIntegrations`.
Unrecognized keys: [flare_flutter]; supported keys: [image, flutter_svg, rive, lottie]
package:json_annotation/src/checked_helpers.dart 66:5                   $checkedNew
package:json_annotation/src/checked_helpers.dart 30:10                  $checkedCreate
package:flutter_gen_core/settings/pubspec.g.dart 182:5                  _$FlutterGenIntegrationsFromJson
package:flutter_gen_core/settings/pubspec.dart 167:7                    new FlutterGenIntegrations.fromJson
package:flutter_gen_core/settings/pubspec.g.dart 99:61                  _$FlutterGenFromJson.<fn>.<fn>
package:json_annotation/src/checked_helpers.dart 87:20                  $checkedConvert
package:json_annotation/src/checked_helpers.dart 28:7                   $checkedCreate.checkedConvert
package:flutter_gen_core/settings/pubspec.g.dart 98:40                  _$FlutterGenFromJson.<fn>
package:json_annotation/src/checked_helpers.dart 33:22                  $checkedCreate.<fn>
package:json_annotation/src/checked_helpers.dart 51:23                  $checkedNew
package:json_annotation/src/checked_helpers.dart 30:10                  $checkedCreate
package:flutter_gen_core/settings/pubspec.g.dart 65:46                  _$FlutterGenFromJson
package:flutter_gen_core/settings/pubspec.dart 65:44                    new FlutterGen.fromJson
package:flutter_gen_core/settings/pubspec.g.dart 20:48                  _$PubspecFromJson.<fn>.<fn>
package:json_annotation/src/checked_helpers.dart 87:20                  $checkedConvert
package:json_annotation/src/checked_helpers.dart 28:7                   $checkedCreate.checkedConvert
package:flutter_gen_core/settings/pubspec.g.dart 19:38                  _$PubspecFromJson.<fn>
package:json_annotation/src/checked_helpers.dart 33:22                  $checkedCreate.<fn>
package:json_annotation/src/checked_helpers.dart 51:23                  $checkedNew
package:json_annotation/src/checked_helpers.dart 30:10                  $checkedCreate
package:flutter_gen_core/settings/pubspec.g.dart 9:40                   _$PubspecFromJson
package:flutter_gen_core/settings/pubspec.dart 15:41                    new Pubspec.fromJson
package:flutter_gen_core/settings/config.dart 82:27                     loadPubspecConfig
package:flutter_gen_core/settings/config.dart 88:12                     loadPubspecConfigOrNull
package:flutter_gen_runner/flutter_gen_runner.dart 29:24                FlutterGenBuilder._config
package:flutter_gen_runner/flutter_gen_runner.dart                      FlutterGenBuilder._config
package:flutter_gen_runner/flutter_gen_runner.dart 56:9                 FlutterGenBuilder.buildExtensions
package:build_runner_core/src/package_graph/apply_builders.dart 403:33  _validateBuilder
package:build_runner_core/src/package_graph/apply_builders.dart 183:9   new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner_core/src/package_graph/apply_builders.dart 346:27  _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                               Iterable.toList
package:build_runner_core/src/package_graph/apply_builders.dart 293:8   createBuildPhases
package:build_runner_core/src/generate/build_impl.dart 109:29           BuildImpl.create
package:build_runner/src/generate/watch_impl.dart 347:42                WatchImpl._run.<fn>"
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
