### ISSUE TITLE
[BUG]: AssetGenImage is still being generated

### ISSUE THREAD

**Issue by msxenon** [FlutterGen/flutter_gen#674]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

5.10.0

### Command type

Dart command

### What happened?

Hey there!
I need it to generate paths only without `AssetGenImage`, so after turning it off -- its still being generated, I think this issue has been solved in https://github.com/FlutterGen/flutter_gen/pull/645, So any solution please?

### Relevant a pubspec.yaml.

```yaml
flutter_gen:
  assets:
    enabled: true
    outputs:
      class_name: AppAssets
      style: camel-case
  integrations:
    image: false
    flutter_svg: false
    rive: false
    lottie: false
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
