### ISSUE TITLE
Null safety support for generated files

### ISSUE THREAD

**Issue by mark-apn** [FlutterGen/flutter_gen#75]
When I run the generator against a project with sdk constraints set to a version with nullability on (>=2.12-0-0) I expect that the generated code is compatible with the null safety features. It is not at the moment. 

I created a bash script workaround that will add the ```@dart=2.10``` comment on top.

```bash
#!/bin/bash

fluttergen

sed -i '' '1 s/^/\/\/@dart=2.10\n/' lib/core/assets/assets.gen.dart
```

I currently don't have time to submit a PR with updated functionality, but if someone else is struggling with this, they can use the workaround until a compatible version is released.

**Comment by britannio** [comment]
@wasabeef Any eta on generating null safe code?

**Comment by wasabeef** [comment]
@britannio 
It will be released in a few days.
https://github.com/FlutterGen/flutter_gen/pull/91

**Comment by wasabeef** [comment]
@mark-apn @britannio 

I'm sorry for the late reply.

Just now we released `v3.0.2` null safety so could you try it?

- Null Safety
- Rename package for build_runner

```yaml
flutter_gen:
  null_safety: true # Optional (default: true)

dev_dependencies:
  build_runner: 
  flutter_gen_runner: ^3.0.2 # Since v2, renamed
```
